### ISSUE TITLE
missing OWNERS file 

### ISSUE THREAD

**Issue by nirrozenbaum** [open-cluster-management/hub-of-hubs-postgresql#2]
openshift bot cannot automatically assign a reviewer for PR when this file is missing

**Comment by vadimeisenbergibm** [comment]
Done https://github.com/open-cluster-management/hub-of-hubs-postgresql/commit/93abfd4ed905fa8513f994d7654f0c5643fc893c

Also for hub-of-hubs-spec-sync and hub-of-hubs-status-sync
