### ISSUE TITLE
required changes on db tables

### ISSUE THREAD

**Issue by nirrozenbaum** [open-cluster-management/hub-of-hubs-postgresql#5]
please see below list for required changes in postgresql tables:
- [x] remove enforcement + resourceVersion from status compliance table.
- [x]  remove the use of default error value in MC status table.
- [x] remove enforcement from aggregated compliance table.
- [x] remove created_at + updated_at + triggers from MC status table.
- [x] remove created_at + updated_at + triggers from aggregated compliance status table.
- [x] remove deleted field from local spec tables.
- [ ] ~add resourceVersion field to local spec tables~.
- [ ] ~for consistency purposes, change order of fields in subscription status table (payload before resource_version).~
- [x] remove resource_version from MC and subscription status tables
- [x] remove cluster_name from MC status table

**Comment by vadimeisenbergibm** [comment]
Done by https://github.com/open-cluster-management/hub-of-hubs-postgresql/commit/251b5f6410fe6d760c2408219a7a6a51223f2088
