### ISSUE TITLE
open points in postgresql db definition

### ISSUE THREAD

**Issue by nirrozenbaum** [open-cluster-management/hub-of-hubs-postgresql#6]
1. in status MC table, we've created an index on cluster name, mentioning this field is unique.  
https://github.com/open-cluster-management/hub-of-hubs-postgresql/blob/main/roles/install/tasks/create_status_tables.yaml#L31-L41
having a unique cluster name was an assumption we made along the way during our development, but in practice cluster name is unique only inside a specific LH. I think it's ok defining MC name is unique across all LHs if we want, but this has to be well documented somewhere cause this is not the expected behavior. alternatively, we can define that the tuple (leaf_hub_name, cluster_name) is unique instead of cluster_name only which I think this is the better decision.

1. in status heartbeats table, field `name` is not consistent with other tables. we should change field `name` to be `leaf_hub_name` for consistency purpose.
https://github.com/open-cluster-management/hub-of-hubs-postgresql/blob/main/roles/install/tasks/create_status_tables.yaml#L89

1. remove propagation_state from status subscriptions table. this information can be found in payload.
https://github.com/open-cluster-management/hub-of-hubs-postgresql/blob/main/roles/install/tasks/create_status_tables.yaml#L102

1. in status subscription table, change field `id` to `subscription_id` for consistency purpose. this is the same as we do with `policy_id` in status compliance table. the only place we're using just `id` is in spec tables, where schema is generic.
https://github.com/open-cluster-management/hub-of-hubs-postgresql/blob/main/roles/install/tasks/create_status_tables.yaml#L100

1. why do we have an index on `resourceVersion` field in status subscriptions table?
https://github.com/open-cluster-management/hub-of-hubs-postgresql/blob/main/roles/install/tasks/create_status_tables.yaml#L107
looks like a mistake.. unless there is a good explanation, this index should be removed.
I believe the intention was to create an index on (leaf_hub_name, subscription_id)

1. in status compliance table, I believe the index on (leaf_hub_name, cluster_name, policy_id) can be removed. 
https://github.com/open-cluster-management/hub-of-hubs-postgresql/blob/main/roles/install/tasks/create_status_policies_table.yaml#L58-L67
this index was part of our performance tests where we wanted to see if additional index would help. we didn't see any difference in results. in addition there is already a different index defined on (policy_id,leaf_hub_name,cluster_name). I don't think we need them both (defined on the same set of fields).

1. I think we should use a single `local` schema instead of `local_spec` + `local_status`. inside the `local` schema we may define tables `policies_spec` + `placementrules_spec` + `compliance_status`. it makes more sense to me in case we would want to send also placement rules status and not only spec (spec + status in the same CR) or alternatively send a different local resource that makes sense to store spec+status together (e.g. apps/subscription for local apps).  
if you disagree we can leave existing schemas for now to see where it takes us and decide on changes later.

**Comment by vadimeisenbergibm** [comment]
Regarding 1: if we do not have unique cluster names, how can we be transparent in presentation? (UI/CLI) The users will have to become aware that leaf hubs are used. @nirnaaman what do you think?

**Comment by vadimeisenbergibm** [comment]
Regarding 3: @golanshabi are you OK with removing `propagation_state`?

**Comment by vadimeisenbergibm** [comment]
Regarding 2,4: the rationale for names is as follows. If you have a table of policies and a single column of ID (the id of the policy), it should be called `id` and not `policy_id`. If there are multiple ids, for example previously we have policy ID and leaf hub ID, then to prevent confusion `policy_id` and `leaf_hub_id` were used. So I propose to rename `policy_id` into `id` in the policy compliance table.

**Comment by nirrozenbaum** [comment]
> Regarding 3: @golanshabi are you OK with removing `propagation_state`?

verified with Golan before adding this point.

**Comment by nirrozenbaum** [comment]
> Regarding 2,4: the rationale for names is as follows. If you have a table of policies and a single column of ID (the id of the policy), it should be called `id` and not `policy_id`. If there are multiple ids, for example previously we have policy ID and leaf hub ID, then to prevent confusion `policy_id` and `leaf_hub_id` were used. So I propose to rename `policy_id` into `id` in the policy compliance table.

acceptable by me as well. just think we should stay consistent.

**Comment by vadimeisenbergibm** [comment]
Regarding 7: I prefer `local_spec` and `local_status` schemas for symmetry with `spec` and `status`. For example, you have identical compliance tables: `status.compliance` and `local_status.compliance`.

**Comment by vadimeisenbergibm** [comment]
Regarding 6: @nirrozenbaum @golanshabi please decide which fields of the payload you need to access frequently, e.g. `resourceVersion` and I will define indexes for these fields.

**Comment by vadimeisenbergibm** [comment]
Regarding 6:

Note the following: https://www.postgresql.org/docs/8.3/indexes-multicolumn.html
> A multicolumn B-tree index can be used with query conditions that involve any subset of the index's columns, but the index is most efficient when there are constraints on the leading (leftmost) columns...

There could be different queries with different subsets of columns where these two different indexes can be used.

**Comment by nirrozenbaum** [comment]
> Regarding 7: I prefer `local_spec` and `local_status` schemas for symmetry with `spec` and `status`. For example, you have identical compliance tables: `status.compliance` and `local_status.compliance`.

that is definitely one aspect to consider.
the other aspect would be - where do we save local CRs if they contain both spec+status?
for example, once we propagate local apps from LH to HoH

> Regarding 1: if we do not have unique cluster names, how can we be transparent in presentation? (UI/CLI) The users will have to become aware that leaf hubs are used. @nirnaaman what do you think?

as I wrote in original issue, I have no problem if MC is the unique identifier. but this has to be well documented to avoid confusions.

**Comment by vadimeisenbergibm** [comment]
Regarding 7:

>   inside the local schema we may define tables policies_spec + placementrules_spec + compliance_status. it makes more sense to me in case we would want to send also placement rules status and not only spec (spec + status in the same CR) or alternatively send a different local resource that makes sense to store spec+status together (e.g. apps/subscription for local apps).

so why do we need `policies_spec` and `compliance_status`, and not just `local.policies`? Do we have cases when for local CRs we need only spec or only status? Is it always both?

**Comment by vadimeisenbergibm** [comment]
Regarding 1:

> as I wrote in original issue, I have no problem if MC is the unique identifier. but this has to be well documented to avoid confusions.

So let's decide on it. @nirnaaman ?

**Comment by nirrozenbaum** [comment]
> so why do we need policies_spec and compliance_status, and not just local.policies? Do we have cases when for local CRs we need only spec or only status? Is it always both?

specifically for policies, we've implemented an optimization using different bundles (sending first clusters per policy and then compliance status where only non compliant are sent).
since we wanted to reuse the mechanism we did for global policies also for local policies, spec/status are kept separately, as it is in the global tables.
that being said, I'm not sure we can say this is the general case. for some CRs we would probably need spec+status together saving only the CR content as json payload.

**Comment by vadimeisenbergibm** [comment]
So we have two options:
1. Having `local` schema with the following tables:
* `local.policies_spec`, 
* `local.compliance_status`
* `local.subscriptions`
1. Having three schemas:
* `local_spec.policies`
* `local_status.compliance`
* `local.subscriptions`

So in the first case we use `spec` and `status` as a suffix in the table name, in the second case we use `spec` and `status` as a suffix in the schema name. I am not sure the first option is better than the second one.

**Comment by vadimeisenbergibm** [comment]
It occurred to me that we have Managed Clusters table with both spec and status in the `status` schema. So we can do the same for CRs that contain both spec and status in `local_status` schema.

**Comment by nirrozenbaum** [comment]
right, ok. 
so local_spec should be used only in cases where we save spec only. 
and local_status is saved for cases where save status information, could be with or without spec part.
sounds reasonable.

**Comment by nirrozenbaum** [comment]
@vadimeisenbergibm from what I see in the list, all issues were addressed except for point (1) which we can decide on separately.
unless you see any open point, this issue can be closed as done.
